#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# ──────────────────────────────────────────────────────────────────────────
# Extend the live Fly volume 5GB -> 10GB.
#
# **Every verification here reads `statvfs` on the box, not the size Fly
# reports.** Those two disagreed for three days on 2026-08-19, and on
# 2026-09-01 an extend was believed done while all three reads still said 5GB.
# A reported size is a claim about intent; `statvfs` is the filesystem.
#
# Nothing here is destructive. A Fly volume can only GROW -- there is no
# shrink -- so the one-way part is the money, not the data.
# ──────────────────────────────────────────────────────────────────────────

APP="kalshi-cockpit"
VOL="vol_42k6qx2z5qdq3m14"
MACHINE="7812601a239428"
TARGET_GB=10
RATE_MB_PER_DAY=161.40   # docs/measurements/2026-09-01-the-volume-clock.md

# _statvfs_field NAME — the authoritative read, in bytes. Echoes nothing on
# failure and **always returns 0**.
#
# The `|| true` and the explicit `return 0` are load-bearing under the
# template's `set -euo pipefail`, and the first version of this wizard died
# for want of them: `flyctl ssh console` exits non-zero on Git Bash even when
# it hands back the data ("Error: The handle is invalid."), so
# `VAR=$(_statvfs_field ...)` aborted the whole script at the assignment --
# *before* the `if [[ -z "$VAR" ]]` check written to catch exactly that.
#
# The guard existed and could not fire. Under `set -e` a function that can
# return non-zero has to be made total at its own boundary, because every
# caller's error handling is downstream of an exit that already happened.
_statvfs_field() {
  local out=""
  out=$(flyctl ssh console -a "$APP" \
          -C "python /app/scripts/inspect_live_disk.py --json" 2>/dev/null \
        | python -c "
import sys, json
s = sys.stdin.read()
try:
    print(json.loads(s[s.index('{'):])['capacity']['$1'])
except Exception:
    pass
" 2>/dev/null) || true
  printf '%s' "$out"
  return 0
}

banner "Extend the live Fly volume: 5GB -> ${TARGET_GB}GB"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight - who you are, and what the volume is right now"
say "Checking flyctl is installed and authenticated."
if ! command -v flyctl >/dev/null 2>&1; then
  warn "flyctl is not on PATH. Install it, then re-run this wizard."
  exit 1
fi
if ! flyctl auth whoami >/dev/null 2>&1; then
  warn "flyctl is not authenticated."
  say "Run this in another terminal, then come back:"
  note "  flyctl auth login"
  pause "Press Enter once you are logged in."
fi
say "Logged in as: $(flyctl auth whoami 2>/dev/null || echo unknown)"
printf '\n'
say "Recording the BEFORE state, so the verify steps compare against real numbers."
BEFORE_API=$(flyctl volumes show "$VOL" -a "$APP" 2>/dev/null | grep -i "Size GB" | tr -dc '0-9' || true)
say "  Fly reports:   ${BEFORE_API:-unknown} GB"
say "  Reading statvfs on the box (this takes a few seconds)..."
BEFORE_TOTAL=$(_statvfs_field total_bytes)
BEFORE_FREE=$(_statvfs_field free_bytes)
if [[ -z "$BEFORE_TOTAL" ]]; then
  warn "Could not read statvfs. That is a refusal, not a zero -- do NOT proceed."
  note "The box may be down, or the SSH path may be blocked. Check: flyctl status -a $APP"
  exit 1
fi
say "  statvfs total: $BEFORE_TOTAL bytes"
say "  statvfs free:  $BEFORE_FREE bytes"
printf '\n'
note "If 'Fly reports' and 'statvfs total' already disagree, stop and say so --"
note "that is the 2026-08-19 failure and it needs diagnosing, not extending."
pause "Numbers look right? Press Enter."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Snapshots - confirm there is a way back"
say "An extend is non-destructive and cannot shrink, so this is belt-and-braces."
say "But the volume holds the entire record, so we check before touching it."
printf '\n'
{ flyctl volumes snapshots list "$VOL" -a "$APP" 2>&1 | head -8; } || \
  warn "Could not list snapshots -- note it and decide whether to continue."
printf '\n'
note "Scheduled snapshots are on with 5-day retention (checked 2026-09-01)."
if ! confirm "Happy to continue?"; then
  say "Stopped. Nothing has changed."
  exit 0
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "The extend - this is the one-way step"
warn "A Fly volume can only grow. There is no shrink, and this costs money."
say "About 15 cents per GB per month, so 5 -> ${TARGET_GB}GB is roughly +75c/month."
printf '\n'
say "At the measured ${RATE_MB_PER_DAY} MB/day, ${TARGET_GB}GB buys you until"
say "roughly mid-November -- against ~2026-09-17 as things stand."
printf '\n'
say "The command about to run:"
note "  flyctl volumes extend $VOL -s $TARGET_GB -a $APP"
printf '\n'
if ! confirm "Run it?"; then
  say "Stopped. Nothing has changed."
  exit 0
fi
printf '\n'
flyctl volumes extend "$VOL" -s "$TARGET_GB" -a "$APP" 2>&1 | sed 's/^/  /'
EXTEND_RC=${PIPESTATUS[0]}
printf '\n'
if [[ "$EXTEND_RC" -ne 0 ]]; then
  warn "The extend command exited non-zero ($EXTEND_RC)."
  note "Read the output above -- Fly refuses an extend if the volume has"
  note "unattached forks or a pending snapshot restore. Fix that first."
  exit 1
fi
say "Command returned 0. That is NOT confirmation -- the next two stages are."
pause "Press Enter to verify."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Verify 1 of 2 - what Fly's API believes"
AFTER_API=$(flyctl volumes show "$VOL" -a "$APP" 2>/dev/null | grep -i "Size GB" | tr -dc '0-9' || true)
say "Fly now reports: ${AFTER_API:-unknown} GB  (was ${BEFORE_API:-unknown} GB)"
printf '\n'
if [[ "$AFTER_API" == "$TARGET_GB" ]]; then
  say "API agrees with the target."
else
  warn "The API does not report ${TARGET_GB}GB."
  note "Do not continue on the assumption it will catch up. Stop here and report"
  note "this, with the extend output from the previous stage."
  exit 1
fi
pause "Press Enter for the read that actually matters."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Verify 2 of 2 - what the filesystem actually has"
say "This is the authoritative read. The API can say ${TARGET_GB}GB while the guest"
say "filesystem is still on the old block device."
printf '\n'
AFTER_TOTAL=$(_statvfs_field total_bytes)
AFTER_FREE=$(_statvfs_field free_bytes)
if [[ -z "$AFTER_TOTAL" ]]; then
  warn "Could not read statvfs. Unknown is not success -- treat this as unverified."
  exit 1
fi
say "  statvfs total: $AFTER_TOTAL bytes  (was $BEFORE_TOTAL)"
say "  statvfs free:  $AFTER_FREE bytes  (was $BEFORE_FREE)"
printf '\n'
if [[ "$AFTER_TOTAL" -gt "$BEFORE_TOTAL" ]]; then
  say "The filesystem grew. This is done."
  GREW=1
else
  warn "The filesystem has NOT grown, though Fly reports ${TARGET_GB}GB."
  say "This is the expected case when the guest needs a restart to pick up"
  say "the resized device. Stage 6 handles it."
  GREW=0
fi
pause "Press Enter."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Restart if needed, and the final number"
if [[ "$GREW" -eq 1 ]]; then
  say "No restart needed -- the filesystem already reports the new size."
else
  warn "A restart drops the Kalshi WebSocket and pauses the recorder briefly."
  say "The command:"
  note "  flyctl machine restart $MACHINE -a $APP"
  printf '\n'
  if confirm "Restart the machine now?"; then
    flyctl machine restart "$MACHINE" -a "$APP" 2>&1 | sed 's/^/  /'
    printf '\n'
    say "Waiting for the box to come back..."
    sleep 25
    AFTER_TOTAL=$(_statvfs_field total_bytes)
    AFTER_FREE=$(_statvfs_field free_bytes)
    say "  statvfs total: ${AFTER_TOTAL:-unreadable} bytes"
    if [[ -n "$AFTER_TOTAL" && "$AFTER_TOTAL" -gt "$BEFORE_TOTAL" ]]; then
      say "The filesystem grew. This is done."
    else
      warn "Still not grown. Stop and report -- do not retry blindly."
      exit 1
    fi
  else
    warn "Skipped. The volume is extended at the API but the filesystem is not."
    note "Nothing is broken, but you have NOT bought headroom yet."
    exit 0
  fi
fi

printf '\n'
if [[ -n "$AFTER_FREE" ]]; then
  say "Headroom at the measured ${RATE_MB_PER_DAY} MB/day:"
  python -c "
free=$AFTER_FREE
rate=$RATE_MB_PER_DAY*1000*1000
days=free/rate
import datetime
d=datetime.date.today()+datetime.timedelta(days=days)
print(f'    {free:,} bytes free  ->  {days:.1f} days  ->  about {d.isoformat()}')
print('    n = 1 day, and the rate is a FLOOR: NFL and NCAAF widen it.')
" 2>/dev/null || note "  (could not compute)"
fi
printf '\n'
note "Next: the deploy raises auto_extend_size_limit to 20GB, so the net can"
note "fire again. Below the volume's own size it is a disabled net that reads"
note "like a configured one -- which is what let this clock run unnoticed."

finish
