"""Redact the portfolio captures into committable wire-format fixtures.

The repo's rule is that wire-format tests load captured payloads, never
hand-built ones -- and the portfolio captures are the one place that rule
collided with the repo being public: `data/captures/portfolio_*.json` are a
real account's betting history and are gitignored, so
`tests/test_portfolio_poll.py`'s strongest check skipped on every machine but
the one that captured them. This script produces
`tests/fixtures/portfolio_fills_redacted.json` and
`tests/fixtures/portfolio_settlements_redacted.json`: the same envelope, the
same field names, the same VALUE SHAPES, with identity removed.

What is kept exact, because it is the substance a parser must survive:
every money string verbatim (`count_fp` "0.27", `fee_cost` "0.001900" -- the
fractional counts and the sub-deci-cent fee grid are the wire facts the
fixtures exist to pin), every enum (`side`, `action`, `is_taker`,
`market_result`), every field's presence and type.

What is redacted, because it is one person's history on a public venue:
- UUIDs (`fill_id`, `order_id`, `trade_id`) -> sequential synthetic UUIDs
  that keep the format but carry nothing.
- Tickers -> the series prefix (which a parser and the sport classifier need)
  with the game/team suffix replaced by an index. `event_ticker` likewise.
- Timestamps -> rounded down to the UTC hour (`ts` and `created_time` kept
  mutually consistent, since the parser prefers one and falls back to the
  other). The hour preserves ordering and the two-clock shape without
  publishing when each bet was placed.
- `subaccount_number` -> 0.

What this does not establish: anything about fees, results, or strategy.
These fixtures are parser food. Analyses run on the verbatim gitignored
captures, never on these.

Run:  .venv\\Scripts\\python.exe scripts\\redact_captures.py
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CAPTURES = REPO / "data" / "captures"
FIXTURES = REPO / "tests" / "fixtures"


def _synthetic_uuid(index: int) -> str:
    return f"00000000-0000-4000-8000-{index:012d}"


def _redact_ticker(ticker: str, mapping: dict[str, str]) -> str:
    """Keep the series prefix; replace the rest with a stable index."""
    if ticker in mapping:
        return mapping[ticker]
    series = ticker.split("-", 1)[0]
    mapping[ticker] = f"{series}-REDACTED{len(mapping):03d}"
    return mapping[ticker]


def _floor_hour_iso(iso: str) -> tuple[str, int]:
    """The ISO timestamp floored to its UTC hour, plus epoch seconds."""
    parsed = datetime.fromisoformat(iso.replace("Z", "+00:00"))
    floored = parsed.astimezone(timezone.utc).replace(
        minute=0, second=0, microsecond=0
    )
    return floored.strftime("%Y-%m-%dT%H:%M:%SZ"), int(floored.timestamp())


def redact_fills() -> dict:
    capture = json.loads(
        (CAPTURES / "portfolio_fills.json").read_text(encoding="utf-8")
    )
    tickers: dict[str, str] = {}
    out = []
    for i, row in enumerate(capture["payload"]["fills"]):
        row = dict(row)
        row["fill_id"] = _synthetic_uuid(3 * i)
        row["trade_id"] = _synthetic_uuid(3 * i + 1)
        row["order_id"] = _synthetic_uuid(3 * i + 2)
        row["ticker"] = _redact_ticker(row["ticker"], tickers)
        if row.get("market_ticker"):
            row["market_ticker"] = _redact_ticker(row["market_ticker"], tickers)
        row["subaccount_number"] = 0
        iso, epoch = _floor_hour_iso(row["created_time"])
        row["created_time"], row["ts"] = iso, epoch
        out.append(row)
    return {
        "note": (
            "REDACTED wire-format fixture, generated by "
            "scripts/redact_captures.py from a real /portfolio/fills "
            "capture. Money strings verbatim; identity removed. "
            "Parser food only -- analyses use the gitignored capture."
        ),
        "endpoint": capture.get("endpoint"),
        "payload": {"fills": out},
    }


def redact_settlements() -> dict:
    capture = json.loads(
        (CAPTURES / "portfolio_settlements.json").read_text(encoding="utf-8")
    )
    tickers: dict[str, str] = {}
    out = []
    for row in capture["payload"]["settlements"]:
        row = dict(row)
        row["ticker"] = _redact_ticker(row["ticker"], tickers)
        if row.get("event_ticker"):
            row["event_ticker"] = _redact_ticker(row["event_ticker"], tickers)
        iso, _ = _floor_hour_iso(row["settled_time"])
        row["settled_time"] = iso
        out.append(row)
    return {
        "note": (
            "REDACTED wire-format fixture, generated by "
            "scripts/redact_captures.py from a real /portfolio/settlements "
            "capture. Money strings verbatim; identity removed. "
            "Parser food only -- analyses use the gitignored capture."
        ),
        "endpoint": capture.get("endpoint"),
        "payload": {"settlements": out},
    }


def main() -> None:
    fills = redact_fills()
    settlements = redact_settlements()
    (FIXTURES / "portfolio_fills_redacted.json").write_text(
        json.dumps(fills, indent=1) + "\n", encoding="utf-8"
    )
    (FIXTURES / "portfolio_settlements_redacted.json").write_text(
        json.dumps(settlements, indent=1) + "\n", encoding="utf-8"
    )
    print(
        f"wrote {len(fills['payload']['fills'])} fills, "
        f"{len(settlements['payload']['settlements'])} settlements"
    )


if __name__ == "__main__":
    main()
