#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# Install a new The Odds API key, locally and on the live Fly app.
#
# The key must never be echoed, logged, or pasted into an agent transcript.
# `tasks/lessons.md` records a live Odds API key reaching a terminal transcript
# because httpx logs full request URLs and this provider takes its credential
# as a *query parameter*; the key was rotated. That is the whole reason this is
# a script you run rather than a value you hand to Claude.
#
# Two extra precautions beyond hidden entry, both because the credential can
# only travel in a URL:
#
#   - curl reads the request from a temp config file (mode 600, removed on
#     exit) instead of taking the URL on the command line, so the key is not
#     visible in `ps` to other processes while the call is in flight.
#   - flyctl reads the secret from stdin via `secrets import`, for the same
#     reason -- `flyctl secrets set KEY=value` would put it in the process list.
#
# Safe to re-run. Enter keeps the value already in .env at every prompt.
# ──────────────────────────────────────────────────────────────────────────

# Run from the repo root whatever directory it was invoked from: `ENV_FILE` is
# a relative `.env` and `git check-ignore` reads the cwd, so running this from
# `scripts/` would silently target `scripts/.env` -- a file nothing loads, in a
# directory that is not gitignored.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

APP="kalshi-cockpit"          # the LIVE instance. Demo holds no odds key.
ODDS_BASE="https://api.the-odds-api.com/v4"
EXPECTED_TIER=20000           # the 20K plan, so a wrong-tier key is visible

# Anything the key touches goes here, and only here.
CURL_CONFIG="$(mktemp)"
chmod 600 "$CURL_CONFIG"
trap 'rm -f "$CURL_CONFIG"' EXIT

REMAINING=""

# probe_key KEY -- call /sports and set REMAINING from x-requests-remaining.
# Returns non-zero on any non-200, so a typo is caught here rather than
# becoming a silent 401 on every sweep for the next month.
probe_key() {
  local key="$1" headers status
  printf 'url = "%s/sports"\ndata-urlencode = "apiKey=%s"\nget\n' \
    "$ODDS_BASE" "$key" > "$CURL_CONFIG"

  headers=$(curl -sS --max-time 20 -o /dev/null -D - --config "$CURL_CONFIG" 2>/dev/null) || return 1
  status=$(printf '%s' "$headers" | awk 'NR==1{print $2}')
  REMAINING=$(printf '%s' "$headers" \
    | tr -d '\r' \
    | awk -F': *' 'tolower($1)=="x-requests-remaining"{print $2}')
  [[ "$status" == "200" ]]
}

TOTAL_STAGES=4

banner "The Odds API — install or rotate the 20K key"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Paste the key, and prove it works"
say "Nothing is written until the key has answered a real request."
note "Input is hidden. This script never prints the key back."
open_url "https://the-odds-api.com/account/"
step "Sign in and copy the API key from your account page."
ask_secret ODDS_API_KEY "Paste the API key:"

if [[ -z "${ODDS_API_KEY:-}" ]]; then
  warn "no key entered — nothing changed."
  exit 1
fi

say ""
say "Checking it against ${ODDS_BASE}/sports ..."
if probe_key "$ODDS_API_KEY"; then
  printf '  %s✓ the key works%s\n' "$GREEN" "$RESET"
  # The numeric test is guarded on the *shape* of the header, not just on it
  # being non-empty: `(( ))` on a non-numeric string aborts under `set -e`, and
  # a wizard that dies here would look like a rejected key.
  if [[ "$REMAINING" =~ ^[0-9]+$ ]]; then
    printf '  %s✓ credits remaining this period: %s%s\n' "$GREEN" "$REMAINING" "$RESET"
    if (( REMAINING > EXPECTED_TIER )); then
      warn "that is above the ${EXPECTED_TIER} plan — a larger tier than expected."
    elif (( REMAINING < EXPECTED_TIER / 2 )); then
      warn "well under ${EXPECTED_TIER}. Either this month is part-spent, or this"
      warn "is the old free-tier key. Check before continuing."
    fi
  else
    warn "no x-requests-remaining header — cannot confirm the tier."
  fi
else
  warn "that key did not return 200. Nothing has been written."
  warn "Check for a stray space or a truncated paste, then re-run."
  exit 1
fi
confirm "Store this key locally and on the live instance?" || { say "Nothing changed."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Write it to the local .env"
say "Used by scripts and tests on this machine. Never committed."

if git -C . check-ignore -q "$ENV_FILE" 2>/dev/null; then
  printf '  %s✓ %s is gitignored%s\n' "$GREEN" "$ENV_FILE" "$RESET"
  write_env ODDS_API_KEY "$ODDS_API_KEY"
else
  warn "$ENV_FILE is NOT gitignored — refusing to write a live key into it."
  warn "Fix .gitignore first. This repo is intended to go public."
  SKIPPED+=("local $ENV_FILE (not gitignored)")
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Set the Fly secret on the live instance"
say "App: $APP   (the demo instance holds no odds key and needs none)"
warn "Setting a secret RESTARTS the machine. Brief downtime, no data loss."

if ! command -v flyctl >/dev/null 2>&1; then
  warn "flyctl is not on PATH."
  say "Set it from the dashboard instead — the phone works fine for this:"
  open_url "https://fly.io/apps/$APP/secrets"
  step "New secret → name ODDS_API_KEY → paste the key → Save."
  warn "SAVING ONLY STAGES IT. The machine does not restart and the loop"
  warn "keeps using the OLD key indefinitely, while every check passes."
  step "Then click the button named: Deploy secrets. That applies the"
  step "staged value AND restarts the machine. Saving alone does not."
  note "Confirmed live 2026-08-17: after a dashboard save the secret read"
  note "Staged, new digest, old key still in the running process."
  SKIPPED+=("Fly secret ODDS_API_KEY on $APP (flyctl not installed)")
  pause "Press Enter once you have clicked Deploy secrets."
elif confirm "Set ODDS_API_KEY on $APP now?"; then
  # `secrets import` reads KEY=VALUE from stdin, so the key never appears as a
  # command-line argument.
  if printf 'ODDS_API_KEY=%s\n' "$ODDS_API_KEY" | flyctl secrets import --app "$APP"; then
    printf '  %s✓ set%s Fly secret ODDS_API_KEY on %s\n' "$GREEN" "$RESET" "$APP"
    WRITTEN_SECRET+=("ODDS_API_KEY (fly:$APP)")
  else
    warn "flyctl failed. Set it from the dashboard: https://fly.io/apps/$APP/secrets"
    SKIPPED+=("Fly secret ODDS_API_KEY on $APP (flyctl error)")
  fi
else
  SKIPPED+=("Fly secret ODDS_API_KEY on $APP (declined)")
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Confirm the key is live ON THE BOX, not just valid"
say "Two questions, and only the second one is the rotation."
note "This first call goes from THIS machine. It proves the key works."
note "It cannot tell you what the live loop is using."

if probe_key "$ODDS_API_KEY"; then
  printf '  %s✓ %s credits remaining this period%s\n' "$GREEN" "${REMAINING:-unknown}" "$RESET"
else
  warn "the verification call failed on the second attempt."
fi

say ""
say "Now the check that can actually fail:"
if command -v flyctl >/dev/null 2>&1; then
  flyctl secrets list --app "$APP" 2>/dev/null | grep -E "ODDS_API_KEY" || warn "could not read the secret list; check it by hand."
  say ""
  warn "The status must read Deployed. If it reads Staged, the loop is"
  warn "still on the OLD key and nothing has been rotated."
  step "Fix a Staged secret with: flyctl secrets deploy -a $APP"
else
  step "On the dashboard ODDS_API_KEY must show Deployed, not Staged."
fi

say ""
say "Next, and not done by this script:"
note "  - REVOKE THE OLD KEY at https://the-odds-api.com/account/ once you have"
note "    seen a sweep succeed on the new one. Until you do, both are live and"
note "    the compromised one still spends your quota."
note "  - Watch the next sweep land:"
note "      python scripts/inspect_live_db.py credits-day"
note "    Calls should resume, and the sweep log should carry no 401s."
note "  - The budget needs no change. fly.live.toml has carried"
note "    ODDS_DAILY_CREDIT_BUDGET = 700 since 2026-08-23, with the attention"
note "    slice at 300. An earlier version of this note said 16 and told you to"
note "    raise it; that was true when this wizard was written for the first"
note "    install and has been false since."

finish
