#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Where look A lands. `docs/measurements/data/` is gitignored on purpose
# (the 2026-09-05 census result: operator data never enters the repo); the
# stage below checks that with git before writing a byte.
APP="kalshi-cockpit"
LOOK_A_CMD='python /app/scripts/inspect_live_db.py combo-markup --limit 400 --cutoff 2026-10-08T00:00:00Z'
LOOK_A_FILE="docs/measurements/data/2026-10-09-combo-markup-look-a.txt"
HEALTH_CMD='python /app/scripts/fetch_live_route.py /api/health'

# The Claude Code `!` prompt runs this with no terminal attached: `read`
# returns at once and `flyctl auth login` refuses ("requires an interactive
# terminal"). Say so and stop, rather than sprinting through four stages.
if [[ ! -t 0 ]]; then
  printf '\n  This wizard needs a real terminal window, not the Claude Code "!" prompt.\n'
  printf '  Open Git Bash (Start menu -> Git Bash), then run:\n\n'
  printf '    cd "%s"\n' "$(pwd -W 2>/dev/null || pwd)"
  printf '    bash scripts/wizard_fly_login_and_look_a.sh\n\n'
  exit 1
fi

banner "Fly login + the maker-markup look A (ticket #327)"

# ── Stage 1: where things stand ──────────────────────────────────────────
stage "Fly CLI — is it here, and who does it think you are?"
say "Everything that reads the live box goes through flyctl, and its login on"
say "this laptop expired on 2026-10-08 (the saved token was from 2026-09-06)."
if ! command -v flyctl >/dev/null 2>&1; then
  warn "flyctl is not on PATH. Install it first: https://fly.io/docs/flyctl/install/"
  open_url "https://fly.io/docs/flyctl/install/"
  pause "Install it, open a new terminal, re-run this wizard. Press Enter to exit."
  exit 1
fi
note "flyctl found: $(command -v flyctl)"
if whoami_out=$(flyctl auth whoami 2>&1); then
  say "Already logged in as: ${whoami_out}"
  note "Stage 2 will be a no-op; you can press Enter through it."
else
  say "As expected, flyctl says it has no login:"
  note "  ${whoami_out}"
fi
pause

# ── Stage 2: log in ──────────────────────────────────────────────────────
stage "Fly CLI — log in"
say "flyctl will open your browser on fly.io. Sign in with the account that"
say "owns the ${APP} app (the same one the GitHub deploy token belongs to)."
step "When the page says you are logged in, come back here."
step "The terminal line to look for is: successfully logged in as <your email>"
until flyctl auth whoami >/dev/null 2>&1; do
  pause "Press Enter to run 'flyctl auth login' now."
  flyctl auth login || true
  if flyctl auth whoami >/dev/null 2>&1; then
    break
  fi
  warn "flyctl still has no login."
  if ! confirm "Try again?"; then
    warn "Stopping here. Re-run this wizard when you can finish the browser step."
    exit 1
  fi
done
say "Logged in as: $(flyctl auth whoami 2>/dev/null)"
pause

# ── Stage 3: prove the box answers ───────────────────────────────────────
stage "A harmless read — prove the box answers over ssh"
say "This runs the committed health reader on the live box. It reads nothing"
say "but /api/health and writes nothing."
note "flyctl ssh console has been seen to exit 1 after a complete, good read,"
note "so the exit code is ignored here; what matters is the printed line."
pause "Press Enter to run it."
set +e
health_out=$(flyctl ssh console -a "$APP" -C "$HEALTH_CMD" 2>&1)
set -e
printf '%s\n' "$health_out" | tail -n 3
if printf '%s' "$health_out" | grep -q '"status":"ok"'; then
  say "The box answered."
else
  warn "No '\"status\":\"ok\"' in the output above."
  warn "Common causes: the fly agent is not running (try: flyctl agent restart),"
  warn "or the login is for an account that does not own ${APP}."
  if ! confirm "Continue to look A anyway?"; then exit 1; fi
fi
pause

# ── Stage 4: look A, saved locally, taken once ───────────────────────────
stage "Look A — the maker-markup measurement, saved to a gitignored file"
say "The registration (docs/measurements/2026-10-08-preregistration-combo-markup-by-leg-count.md)"
say "allows exactly one look A. Taking it twice is two looks, so this stage"
say "refuses to re-run once the file exists."
if [[ -s "$LOOK_A_FILE" ]]; then
  if grep -qiE "Traceback|Error:" "$LOOK_A_FILE" && ! grep -qiE "leg count|cells|dispersion" "$LOOK_A_FILE"; then
    say "A previous run left an error, not a result, at $LOOK_A_FILE."
    say "An instrument that printed no statistic took no look, so this can be retaken."
    if confirm "Retake look A now (the old error file is replaced)?"; then
      rm -f "$LOOK_A_FILE"
    else
      exit 1
    fi
  else
    say "Look A was already taken: $LOOK_A_FILE ($(wc -c < "$LOOK_A_FILE") bytes)."
    say "Nothing is re-run. Tell Claude the file is there."
    pause "Press Enter to finish."
    finish
    exit 0
  fi
fi
mkdir -p "$(dirname "$LOOK_A_FILE")"
if ! git check-ignore -q "$LOOK_A_FILE"; then
  warn "$LOOK_A_FILE is NOT gitignored. Refusing: this output holds your own asks."
  warn "Add 'docs/measurements/data/' to .gitignore first, then re-run."
  exit 1
fi
say "Target: $LOOK_A_FILE (gitignored: yes)"
say "Command on the box: $LOOK_A_CMD"
note "The instrument is bounded (--limit 400, the registration's cutoff). It may"
note "take a few minutes: a 10,000-resample bootstrap runs for each cell above"
note "the floor."
pause "Press Enter to take look A."
set +e
flyctl ssh console -a "$APP" -C "$LOOK_A_CMD" 2>&1 | tee "$LOOK_A_FILE"
set -e
if [[ ! -s "$LOOK_A_FILE" ]]; then
  warn "The file is empty: the instrument printed nothing. Nothing was recorded"
  warn "as a look. Read the lines above for the error and tell Claude."
  rm -f "$LOOK_A_FILE"
  exit 1
fi
if grep -qiE "Traceback|Error:" "$LOOK_A_FILE" && ! grep -qiE "leg count|cells|dispersion" "$LOOK_A_FILE"; then
  warn "The output looks like an error, not a result. It is kept at $LOOK_A_FILE"
  warn "so Claude can read it, but it is NOT a look. Tell Claude."
  pause "Press Enter to finish."
  finish
  exit 1
fi
say "Saved $(wc -c < "$LOOK_A_FILE") bytes to $LOOK_A_FILE (not tracked by git)."
say "Now tell Claude: \"look A is saved\". Claude writes the result document"
say "from this file and sends it to the measurement-skeptic before any number"
say "enters the record."
pause "Press Enter to finish."

finish
